# PIPELINE DEFINITION
# Name: heart-prediction-lightgbm-train
# Description: XGB training pipeline which:
#              1. Loads data from GCS
#               2. Trains a model via Vertex AI CustomContainerTrainingJob
#               3. Evaluates the model against the current champion model
#               4. If better, the model becomes the new default model
# Inputs:
#    gcs_test_path: str [Default: 'gs://durable-ring-405419_cloudbuild/test.csv']
#    gcs_train_path: str [Default: 'gs://durable-ring-405419_cloudbuild/train.csv']
#    gcs_valid_path: str [Default: 'gs://durable-ring-405419_cloudbuild/valid.csv']
#    model_name: str [Default: 'lightgbm']
#    project_id: str [Default: 'durable-ring-405419']
#    project_location: str [Default: 'us-central1']
# Outputs:
#    train-metrics: system.Metrics
components:
  comp-importer:
    executorLabel: exec-importer
    inputDefinitions:
      parameters:
        uri:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        artifact:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
  comp-importer-2:
    executorLabel: exec-importer-2
    inputDefinitions:
      parameters:
        uri:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        artifact:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
  comp-importer-3:
    executorLabel: exec-importer-3
    inputDefinitions:
      parameters:
        uri:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        artifact:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
  comp-train:
    executorLabel: exec-train
    inputDefinitions:
      artifacts:
        test_data:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        train_data:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        valid_data:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
      parameters:
        hparams:
          parameterType: STRUCT
        label:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        metrics:
          artifactType:
            schemaTitle: system.Metrics
            schemaVersion: 0.0.1
        model:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-importer:
      importer:
        artifactUri:
          runtimeParameter: uri
        reimport: true
        typeSchema:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
    exec-importer-2:
      importer:
        artifactUri:
          runtimeParameter: uri
        reimport: true
        typeSchema:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
    exec-importer-3:
      importer:
        artifactUri:
          runtimeParameter: uri
        reimport: true
        typeSchema:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
    exec-train:
      container:
        args:
        - src.main
        - --train-data
        - '{{$.inputs.artifacts[''train_data''].path}}'
        - --valid-data
        - '{{$.inputs.artifacts[''valid_data''].path}}'
        - --test-data
        - '{{$.inputs.artifacts[''test_data''].path}}'
        - --label
        - '{{$.inputs.parameters[''label'']}}'
        - --model
        - '{{$.outputs.artifacts[''model''].path}}'
        - --metrics
        - '{{$.outputs.artifacts[''metrics''].path}}'
        - --hparams
        - '{{$.inputs.parameters[''hparams'']}}'
        command:
        - python
        - -m
        image: us-central1-docker.pkg.dev/durable-ring-405419/vertex-images/heart-prediction-src-training:latest
pipelineInfo:
  description: "XGB training pipeline which:\n1. Loads data from GCS\n 2. Trains a\
    \ model via Vertex AI CustomContainerTrainingJob\n 3. Evaluates the model against\
    \ the current champion model\n 4. If better, the model becomes the new default\
    \ model"
  name: heart-prediction-lightgbm-train
root:
  dag:
    outputs:
      artifacts:
        train-metrics:
          artifactSelectors:
          - outputArtifactKey: metrics
            producerSubtask: train
    tasks:
      importer:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-importer
        inputs:
          parameters:
            uri:
              componentInputParameter: gcs_train_path
        taskInfo:
          name: Load train data from GCS
      importer-2:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-importer-2
        inputs:
          parameters:
            uri:
              componentInputParameter: gcs_valid_path
        taskInfo:
          name: Load validation data from GCS
      importer-3:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-importer-3
        inputs:
          parameters:
            uri:
              componentInputParameter: gcs_test_path
        taskInfo:
          name: Load test data from GCS
      train:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train
        dependentTasks:
        - importer
        - importer-2
        - importer-3
        inputs:
          artifacts:
            test_data:
              taskOutputArtifact:
                outputArtifactKey: artifact
                producerTask: importer-3
            train_data:
              taskOutputArtifact:
                outputArtifactKey: artifact
                producerTask: importer
            valid_data:
              taskOutputArtifact:
                outputArtifactKey: artifact
                producerTask: importer-2
          parameters:
            hparams:
              runtimeValue:
                constant:
                  learning_rate: 0.01
                  max_depth: 6.0
                  n_estimators: 1500.0
                  num_leaves: 31.0
                  objective: binary
            label:
              runtimeValue:
                constant: HeartDisease
        taskInfo:
          name: Train model
  inputDefinitions:
    parameters:
      gcs_test_path:
        defaultValue: gs://durable-ring-405419_cloudbuild/test.csv
        description: GCS path for test data
        isOptional: true
        parameterType: STRING
      gcs_train_path:
        defaultValue: gs://durable-ring-405419_cloudbuild/train.csv
        description: GCS path for training data
        isOptional: true
        parameterType: STRING
      gcs_valid_path:
        defaultValue: gs://durable-ring-405419_cloudbuild/valid.csv
        description: GCS path for validation data
        isOptional: true
        parameterType: STRING
      model_name:
        defaultValue: lightgbm
        description: name of model
        isOptional: true
        parameterType: STRING
      project_id:
        defaultValue: durable-ring-405419
        description: project id of the Google Cloud project
        isOptional: true
        parameterType: STRING
      project_location:
        defaultValue: us-central1
        description: location of the Google Cloud project
        isOptional: true
        parameterType: STRING
  outputDefinitions:
    artifacts:
      train-metrics:
        artifactType:
          schemaTitle: system.Metrics
          schemaVersion: 0.0.1
schemaVersion: 2.1.0
sdkVersion: kfp-2.7.0
